// log in as CafeOwner
POST https://localhost:7130/auth/login
Content-Type: application/json

{ "Username" : "cafeOwner", "Password" : "test1" }

###
// log in as Entertainer
POST https://localhost:7130/auth/login
Content-Type: application/json

{ "Username" : "art", "Password" : "test1" }

###

// log in as User
POST https://localhost:7130/auth/login
Content-Type: application/json

{ "Username" : "user", "Password" : "test1" }



###

// must be authorized 
GET https://localhost:7130/test/authorized
Authorization: Bearer 

### 

// policy mustbecafeowner allowed 
GET https://localhost:7130/test/must-be-cafe-owner
Authorization: Bearer 

###

GET https://localhost:7130/test/manualcheck
Authorization: Bearer 